#line 1 "DevTooling\\MacroHack.h"
#line 1 "F:\\Users\\Xan\\source\\repos\\RWFirstMod\\XansTools\\DevTooling\\MacroHack.h"
/// <auto-generated>
///	This code was generated by the C Preprocessor. Do not modify this file, as any changes will be overwritten on the next build.
/// </auto-generated>

// Yes, you read that right. A .h file in C#.
// This is a hilariously terrible hack that allows me to use C macros in C#
// Yes, it's terrible, and no, I don't care (that's why I did it anyway).
// A lot of code needed to be copy-pasted to counter-jank RW's jank and the only way to do that without butchering readability was macros.
// Cope, seethe, and mald simultaneously.
// I at least did you the favor of isolating this to its own separate library, so that the garbage doesn't seep into the main code's public API.


	
		
		
	


#line 20 "F:\\Users\\Xan\\source\\repos\\RWFirstMod\\XansTools\\DevTooling\\MacroHack.h"
#line 21 "F:\\Users\\Xan\\source\\repos\\RWFirstMod\\XansTools\\DevTooling\\MacroHack.h"


	
	
	//////////////////////////////////

	

	
	
	

	

	//////////////////////////////////

	

	
	

	
	

	
	

	
	

	
	

	
	

	
	

	
	

	
	

	
	

	
	

	
	
	
	
	
	
	
	
	
	
	
	
	
	
	

	
	
	
	
	
	
	
	
	
	
	
	

	












	












	

#line 130 "F:\\Users\\Xan\\source\\repos\\RWFirstMod\\XansTools\\DevTooling\\MacroHack.h"
#line 1 "F:\\Users\\Xan\\source\\repos\\RWFirstMod\\XansTools\\DevTooling\\MacroHack.h"
/// <auto-generated>
///	This code was generated by the C Preprocessor. Do not modify this file, as any changes will be overwritten on the next build.
/// </auto-generated>

// Yes, you read that right. A .h file in C#.
// This is a hilariously terrible hack that allows me to use C macros in C#
// Yes, it's terrible, and no, I don't care (that's why I did it anyway).
// A lot of code needed to be copy-pasted to counter-jank RW's jank and the only way to do that without butchering readability was macros.
// Cope, seethe, and mald simultaneously.
// I at least did you the favor of isolating this to its own separate library, so that the garbage doesn't seep into the main code's public API.









#line 21 "F:\\Users\\Xan\\source\\repos\\RWFirstMod\\XansTools\\DevTooling\\MacroHack.h"












































































































#line 130 "F:\\Users\\Xan\\source\\repos\\RWFirstMod\\XansTools\\DevTooling\\MacroHack.h"
