using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using UnityEngine;

namespace XansTools.PrimaryToolkit.CompanionData {

	/// <remarks>
	/// Mirror classes allow a standalone or otherwise uninherited class to "inherit" all of the fields and properties for easy access.
	/// </remarks>
	AUTOGENERATED_HEADER
	[CPreprocessorGenerated]
	public abstract class MirrorOracleGraphics {

		public abstract OracleGraphics Mirror { get; }

		ALL_GRAPHICSMODULE_PROPERTIES(Mirror)
		ALL_ORACLEGRAPHICS_MIRROR_PROPERTIES(Mirror)

	}
}
