using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace XansTools.PrimaryToolkit.CompanionData {

	/// <remarks>
	/// Mirror classes allow a standalone or otherwise uninherited class to "inherit" all of the fields and properties for easy access.
	/// </remarks>
	AUTOGENERATED_HEADER
	[CPreprocessorGenerated]
	public abstract class MirrorUpdatableAndDeletable {

		public abstract UpdatableAndDeletable Mirror { get; }

		ALL_UPDATABLEANDDELETABLE_MIRROR_PROPERTIES(Mirror)

	}
}
